// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwtsdeqichanpfilhhsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3dHNkZXFpY2hhbnBmaWxoaHNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2ODA0NjcsImV4cCI6MjA3MDI1NjQ2N30.LMGWfDZz3dC7XPAxTSG9hU8SYOnbhv0wgxofOR85Ejk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});